openapi: 3.0.1
info:
  title: dem-heights
  description: map-colonies service for extracting elevations from DTM/DSM geotiffs
  version: 2.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:
  /points:
    post:
      operationId: pointsHeight
      tags:
        - heights
      summary: get points heights
      requestBody:
        description: Points to calculate heights for.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pointsReq'
            example:
              positions:
                - latitude: 32.80775333333333
                  longitude: 35.21339666666667
                - latitude: 32.80775333333333
                  longitude: 35.22673
              productType: MIXED
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pointsRes'
              example:
                data:
                  - latitude: 32.80775333333333
                    longitude: 35.21339666666667
                    height: 221.09576574778345
                    productId: first_Product
                  - latitude: 32.80775333333333
                    longitude: 35.22673
                    height: 141.7940749310484
                    productId: first_Product
                products:
                  first_Product:
                    productType: QUANTIZED_MESH_DTM_BEST
                    updateDate: '2023-05-08T17:44:01.000Z'
                    resolutionMeter: 30
                    absoluteAccuracyLEP90: 9.e-7
                  second_Product:
                    productType: QUANTIZED_MESH_DTM_BEST
                    updateDate: '2023-05-08T17:44:01.000Z'
                    resolutionMeter: 100
                    absoluteAccuracyLEP90: 9.e-7
            application/octet-stream:
              schema:
                type: string
                format: binary
        '500':
          description: Service Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    error:
      type: object
      required:
        - message
        - errorCode
      properties:
        message:
          type: string
        errorCode:
          oneOf:
            - $ref: '#/components/schemas/errorCodesEnum'
    pointsReq:
      type: object
      required:
        - positions
      properties:
        positions:
          type: array
          items:
            type: object
            required:
              - longitude
              - latitude
            properties:
              longitude:
                type: number
                format: double
              latitude:
                type: number
                format: double
        productType:
          oneOf:
            - $ref: '#/components/schemas/productTypeEnum'
          default: MIXED
    pointsRes:
      type: object
      required:
        - data
      properties:
        data:
          type: array
          items:
            type: object
            required:
              - longitude
              - latitude
              - height
            properties:
              longitude:
                type: number
                format: double
              latitude:
                type: number
                format: double
              height:
                nullable: true
                type: number
                format: double
              productId:
                type: string
        products:
          type: object
          additionalProperties:
            type: object
            properties:
              productType:
                oneOf:
                  - $ref: '#/components/schemas/productTypeEnum'
              resolutionMeter:
                type: number
                format: double
              absoluteAccuracyLEP90:
                type: number
                format: double
              updateDate:
                type: string
                format: date-time
    productTypeEnum:
      type: string
      enum:
        - DSM
        - DTM
        - MIXED
    errorCodesEnum:
      type: string
      enum:
        - POINTS_DENSITY_TOO_LOW_ERROR
        - GENERAL_SERVER_ERROR
